# from collections import OrderedDict
# set_order_dict = OrderedDict( )
set_order_list_excel = [
    "Base set",
    "Jungle",
    "Fossil",
    "Base set 2",
    "Team Rocket",
    "Gym Heroes",
    "Gym Challenge",
    "Neo Genesis",
    "Neo Discovery",
    "Neo Revelation",
    "Neo Destiny",
    "Legendary Collection",
    "Expedition Base Set",
    "Aquapolis",
    "Skyridge",
    "EX Ruby & Saphire",
    "EX Sandstorm",
    "EX Dragon",
    "EX Team Magma vs Team Aqua",
    "Ex Hidden Legends",
    "EX FireRed & LeafGreen",
    "EX Team Rocket Returns",
    "EX Deoxys",
    "EX Emerald",
    "EX Unseen Forces",
    "EX Delta Species",
    "EX Legend Maker",
    "EX Holon Phantoms",
    "EX Crystal Guardians",
    "EX Dragon Frontiers",
    "EX Power Keepers",
    "Diamond & Pearl",
    "Mysterious Treasures",
    "Secret Wonders",
    "Great Encounters",
    "Majestic Dawn",
    "Legends Awakened",
    "Stormfront",
    "Platinum",
    "Rising Rivals",
    "Supreme Victors",
    "Arceus",
    "HeartGold & SoulSilver",
    "Unleashed",
    "Undaunted",
    "Triumphant",
    "Call of Legends",
    "Black & White",
    "Emerging Powers",
    "Noble Victories",
    "Next Destinies",
    "Dark Explorers",
    "Dragons Exalted",
    "Boundaries Crossed",
    "Plasma Storm",
    "Plasma Freeze",
    "Plasma Blast",
    "Legendary Treasures",
    "XY",
    "Flashfire",
    "Furious Fists",
    "Phantom Forces",
    "Primal Clash",
    "Roaring Skies",
    "Ancient Origins",
    "BREAKthrough",
    "BREAKpoint",
    "Fates Collide",
    "Steam Siege",
    "Evolutions",
    "Sun & Moon",
    "Guardians Rising",
    "Burning Shadows",
    "Crimson Invasion",
    "Ultra Prism",
    "Forbidden Light",
    "Celestial Storm",
    "Lost Thunder",
    "Team Up",
    "Unbroken Bonds",
    "Unified Minds",
    "Cosmic Eclipse",
    "Sword & Shield",
    "Rebel Clash",
    "Darkness Ablaze",
    "Vivid Voltage",
    "Battle Styles",
    "Chilling Reign",
    "Evolving Skies",
    "Fusion Strike",
    "Brilliant Stars",
    "Astral Radiance",
    "Lost Origin",
    "Silver Tempest",
    "Scarlet & Violet Base Set",
    "Paldea Evolved",
    "Obsidian Flames",
    "Paradox Rift",
    "Temporal Forces",
    "Twilight Masquerade",
]

set_info = [
    {"name": "Base set", "pedia_name": ""},
    {"name": "Jungle", "pedia_name": ""},
    {"name": "Fossil", "pedia_name": ""},
    {"name": "Base set 2", "pedia_name": ""},
    {"name": "Team Rocket", "pedia_name": ""},
    {"name": "Gym Heroes", "pedia_name": ""},
    {"name": "Gym Challenge", "pedia_name": ""},
    {"name": "Neo Genesis", "pedia_name": ""},
    {"name": "Neo Discovery", "pedia_name": ""},
    {"name": "Neo Revelation", "pedia_name": ""},
    {"name": "Neo Destiny", "pedia_name": ""},
    {"name": "Legendary Collection", "pedia_name": ""},
    {"name": "Expedition", "pedia_name": "Expedition_Base_Set"},
    {"name": "Aquapolis", "pedia_name": ""},
    {"name": "Skyridge", "pedia_name": ""},
    {"name": "Ruby and Sapphire", "pedia_name": "EX_Ruby_&_Sapphire"},
    {"name": "Sandstorm", "pedia_name": "EX_Sandstorm"},
    {"name": "Dragon", "pedia_name": "EX_Dragon"},
    {"name": "Team Magma vs Team Aqua", "pedia_name": "EX_Team_Magma_vs_Team_Aqua"},
    {"name": "Hidden Legends", "pedia_name": "EX_Hidden_Legends"},
    {"name": "FireRed & LeafGreen", "pedia_name": "EX_FireRed_&_LeafGreen"},
    {"name": "Team Rocket Returns", "pedia_name": "EX_Team_Rocket_Returns"},
    {"name": "Deoxys", "pedia_name": "EX_Deoxys"},
    {"name": "Emerald", "pedia_name": "EX_Emerald"},
    {"name": "Unseen Forces", "pedia_name": "EX_Unseen_Forces"},
    {"name": "Delta Species", "pedia_name": "EX_Delta_Species"},
    {"name": "Legend Maker", "pedia_name": "EX_Legend_Maker"},
    {"name": "Holon Phantoms", "pedia_name": "EX_Holon_Phantoms"},
    {"name": "Crystal Guardians", "pedia_name": "EX_Crystal_Guardians"},
    {"name": "Dragon Frontiers", "pedia_name": "EX_Dragon_Frontiers"},
    {"name": "Power Keepers", "pedia_name": "EX_Power_Keepers"},
    {"name": "Diamond and Pearl", "pedia_name": "Diamond_&_Pearl"},
    {"name": "Mysterious Treasures", "pedia_name": ""},
    {"name": "Secret Wonders", "pedia_name": ""},
    {"name": "Great Encounters", "pedia_name": ""},
    {"name": "Majestic Dawn", "pedia_name": ""},
    {"name": "Legends Awakened", "pedia_name": ""},
    {"name": "Stormfront", "pedia_name": ""},
    {"name": "Platinum", "pedia_name": ""},
    {"name": "Rising Rivals", "pedia_name": ""},
    {"name": "Supreme Victors", "pedia_name": ""},
    {"name": "Arceus", "pedia_name": "Platinum:_Arceus"},
    {"name": "HeartGold SoulSilver", "pedia_name": "HeartGold_&_SoulSilver"},
    {"name": "Unleashed", "pedia_name": ""},
    {"name": "Undaunted", "pedia_name": ""},
    {"name": "Triumphant", "pedia_name": ""},
    {"name": "Call of Legends", "pedia_name": ""},
    {"name": "Black & White", "pedia_name": ""},
    {"name": "Emerging Powers", "pedia_name": ""},
    {"name": "Noble Victories", "pedia_name": ""},
    {"name": "Next Destinies", "pedia_name": ""},
    {"name": "Dark Explorers", "pedia_name": ""},
    {"name": "Dragons Exalted", "pedia_name": ""},
    {"name": "Boundaries Crossed", "pedia_name": ""},
    {"name": "Plasma Storm", "pedia_name": ""},
    {"name": "Plasma Freeze", "pedia_name": ""},
    {"name": "Plasma Blast", "pedia_name": ""},
    {"name": "Legendary Treasures", "pedia_name": ""},
    {
        "name": "Legendary Treasures: Radiant Collection",
        "pedia_name": "Legendary Treasures",
    },
    {"name": "XY Base Set", "pedia_name": "XY"},
    {"name": "XY - Flashfire", "pedia_name": "Flashfire"},
    {"name": "XY - Furious Fists", "pedia_name": "Furious Fists"},
    {"name": "XY - Phantom Forces", "pedia_name": "Phantom Forces"},
    {"name": "XY - Primal Clash", "pedia_name": "Primal Clash"},
    {"name": "XY - Roaring Skies", "pedia_name": "Roaring Skies"},
    {"name": "XY - Ancient Origins", "pedia_name": "Ancient Origins"},
    {"name": "XY - BREAKthrough", "pedia_name": "BREAKthrough"},
    {"name": "XY - BREAKpoint", "pedia_name": "BREAKpoint"},
    {"name": "XY - Fates Collide", "pedia_name": "Fates Collide"},
    {"name": "XY - Steam Siege", "pedia_name": "Steam Siege"},
    {"name": "XY - Evolutions", "pedia_name": "Evolutions"},
    {"name": "SM Base Set", "pedia_name": "Sun & Moon"},
    {"name": "SM - Guardians Rising", "pedia_name": "Guardians Rising"},
    {"name": "SM - Burning Shadows", "pedia_name": "Burning Shadows"},
    {"name": "SM - Crimson Invasion", "pedia_name": "Crimson Invasion"},
    {"name": "SM - Ultra Prism", "pedia_name": "Ultra Prism"},
    {"name": "SM - Forbidden Light", "pedia_name": "Forbidden Light"},
    {"name": "SM - Celestial Storm", "pedia_name": "Celestial Storm"},
    {"name": "SM - Lost Thunder", "pedia_name": "Lost Thunder"},
    {"name": "SM - Team Up", "pedia_name": "Team Up"},
    {"name": "SM - Unbroken Bonds", "pedia_name": "Unbroken Bonds"},
    {"name": "SM - Unified Minds", "pedia_name": "Unified Minds"},
    {"name": "SM - Cosmic Eclipse", "pedia_name": "Cosmic Eclipse"},
    {"name": "SWSH01: Sword & Shield Base Set", "pedia_name": "Sword & Shield"},
    {"name": "SWSH02: Rebel Clash", "pedia_name": "Rebel Clash"},
    {"name": "SWSH03: Darkness Ablaze", "pedia_name": "Darkness Ablaze"},
    {"name": "SWSH04: Vivid Voltage", "pedia_name": "Vivid Voltage"},
    {"name": "SWSH05: Battle Styles", "pedia_name": "Battle Styles"},
    {"name": "SWSH06: Chilling Reign", "pedia_name": "Chilling Reign"},
    {"name": "SWSH07: Evolving Skies", "pedia_name": "Evolving Skies"},
    {"name": "SWSH08: Fusion Strike", "pedia_name": "Fusion Strike"},
    {"name": "SWSH09: Brilliant Stars", "pedia_name": "Brilliant Stars"},
    {
        "name": "SWSH09: Brilliant Stars Trainer Gallery",
        "pedia_name": "Brilliant Stars",
    },
    {"name": "SWSH10: Astral Radiance", "pedia_name": "Astral Radiance"},
    {
        "name": "SWSH10: Astral Radiance Trainer Gallery",
        "pedia_name": "Astral Radiance",
    },
    {"name": "SWSH11: Lost Origin", "pedia_name": "Lost Origin"},
    {"name": "SWSH11: Lost Origin Trainer Gallery", "pedia_name": "Lost Origin"},
    {"name": "SWSH12: Silver Tempest", "pedia_name": "Silver Tempest"},
    {"name": "SWSH12: Silver Tempest Trainer Gallery", "pedia_name": "Silver Tempest"},
    {"name": "SV01: Scarlet & Violet Base Set", "pedia_name": "Scarlet & Violet"},
    {"name": "SV02: Paldea Evolved", "pedia_name": "Paldea Evolved"},
    {"name": "SV03: Obsidian Flames", "pedia_name": "Obsidian Flames"},
    {"name": "SV04: Paradox Rift", "pedia_name": "Paradox Rift"},
    {"name": "SV05: Temporal Forces", "pedia_name": "Temporal Forces"},
    {"name": "SV06: Twilight Masquerade", "pedia_name": "Twilight Masquerade"},
    {"name": "SV07: Stellar Crown", "pedia_name": "Stellar Crown"},
    {"name": "SV08: Surging Sparks", "pedia_name": "Surging Sparks"},
]


def get_set_name_list():
    return [item["name"] for item in set_info]


def get_set_count():
    return len(set_info)


def get_set_index_by_name(set_name):
    set_name_list = get_set_name_list()
    if set_name in set_name_list:
        return set_name_list.index(set_name)
    return None


def get_set_name_by_index(index):
    return set_info[index]["name"]
